### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ShashankJais128**
added everything of task-1

### CODE REVIEW

**Comment by Tamanna-S** [comment]
hey!
may we delete the index.html and create from scratch?
or we have to update only?

**Comment by shakthilahiru** [comment]
just update

**Comment by Tamanna-S** [comment]
may i delete this:
 <p style="color: blue;">Piyumath Sasmitha</p>
<h1>Costa x Duava - Gammane [ගම්මානේ]</h1>
<p>saah weeew. oya thama hodatama kare.</p>

**Comment by Tamanna-S** [comment]
or not?

**Comment by shakthilahiru** [comment]
Create a new folder and rename it with your name then add an index.html page

**Comment by Tamanna-S** [comment]
okay..thanks😊

**Pull request merged**
